# Generated by Django 4.0.4 on 2023-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='subject',
        ),
    ]
