# Generated by Django 4.0.4 on 2023-01-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0002_rename_phonenumber_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
