# Generated by Django 4.0.4 on 2023-01-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0004_remove_contact_id_contact_contact_id_contact_memail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='memail',
        ),
    ]
