# Generated by Django 4.0.4 on 2023-01-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0005_remove_contact_memail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
