# Generated by Django 4.0.4 on 2023-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0006_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(default='', max_length=20)),
                ('product_sub_category', models.CharField(default='', max_length=20)),
                ('product_desc', models.CharField(max_length=500)),
                ('product_price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
