# Generated by Django 4.0.4 on 2023-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0008_orders_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100 TO 300', '100 TO 300'), ('300 TO 500', '300 TO 500'), ('500 TO 700', '500 TO 700'), ('700 TO 900', '700 TO 900'), ('900 TO 1200', '900 TO 1200'), ('1200 TO 1500', '1200 TO 1500'), ('1500 +', '1500 +')], max_length=100)),
            ],
        ),
    ]
