# Generated by Django 4.0.4 on 2023-03-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0011_producte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producte',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='producte',
            name='product_sub_category',
        ),
    ]
