# Generated by Django 4.0.4 on 2023-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0012_remove_producte_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('100ml', '100ml'), ('300ml', '300ml'), ('500ml', '500ml'), ('700ml', '700ml'), ('900ml', '900ml'), ('1200ml', '1200ml'), ('1500ml', '1500ml')], max_length=100)),
            ],
        ),
    ]
