# Generated by Django 4.0.4 on 2023-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0013_volume_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume_filter',
            old_name='price',
            new_name='Volume',
        ),
    ]
