# Generated by Django 4.0.4 on 2023-03-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0014_rename_price_volume_filter_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='producte',
            name='volume_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.volume_filter'),
        ),
    ]
