# Generated by Django 4.0.4 on 2023-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0017_producte_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume_filter',
            name='Volume',
            field=models.CharField(max_length=100),
        ),
    ]
