# Generated by Django 4.0.4 on 2023-03-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0019_alter_products_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producte',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='producte',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producte',
            old_name='product_price',
            new_name='price',
        ),
    ]
