# Generated by Django 4.0.4 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0020_rename_product_image_producte_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
