# Generated by Django 4.0.4 on 2023-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0021_alter_producte_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
