# Generated by Django 4.0.4 on 2023-03-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0022_alter_products_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='price',
            field=models.FloatField(),
        ),
    ]
