# Generated by Django 4.0.4 on 2023-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0023_alter_producte_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producte',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
