# Generated by Django 4.0.4 on 2023-03-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0024_alter_producte_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producte',
            new_name='Product',
        ),
    ]
