# Generated by Django 4.0.4 on 2023-03-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0027_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(default='', max_length=20)),
                ('product_sub_category', models.CharField(default='', max_length=20)),
                ('product_desc', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
