# Generated by Django 4.0.4 on 2023-03-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0028_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
