# Generated by Django 4.0.4 on 2023-03-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0030_rename_address1_order_address_remove_order_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Variant',
        ),
        migrations.CreateModel(
            name='Price_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.product')),
            ],
        ),
    ]
