# Generated by Django 4.0.4 on 2023-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0031_rename_tag_variant_price_var'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='tag',
            new_name='volume',
        ),
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Price_var',
        ),
    ]
