# Generated by Django 4.0.4 on 2023-03-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0032_rename_tag_variant_volume_variant_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='volume_filter',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='volume',
        ),
        migrations.AddField(
            model_name='variant',
            name='volume_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.volume_filter'),
        ),
    ]
