# Generated by Django 4.0.4 on 2023-05-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerceapp', '0034_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecommerceapp.volume_filter'),
        ),
    ]
